from enum import Enum


class LogsAction(str, Enum):
    DEFAULT = "default"
    START = "start_command"
    AUTH_SUCCESS = "auth_success"
    AUTH_FAIL = "auth_fail"
    BLOCKED = "blocked"
    FILE_SYSTEM = "file_system"
    SYSTEM_ACTION = "system_action"
    LOGS = "logs"
    BACK_TO_FILE_SYSTEM = "back_to_main_menu"
    BACK_TO_MAIN_MENU = "back_to_main_menu"
    DELETE_MENU = "delete_menu"
    CHANGE_MENU = "change_menu"
    SEND_MENU = "send_menu"
    CREATE_MENU = "create_menu"
    DELETE = "delete_path"
    CHANGE = "change_path"
    SEND = "send_path"
    CREATE = "create_path"
    PARENT_DIRECTORY = "back_to_parent_directory"
    WAKE_UP = "wake_up"
    WORKING_TIME = "working_time"
    LOADING_COMPONENTS = "check_loading"
    TAKE_SCREENSHOT = "take_screenshot"
    ALL_PROCESSES = "take_all_processes"
    BACK_TO_SYS_ACTIONS = "back_to_sys_actions"
    KILL_PROCESSES = "killed_processes"
    ENTRY_PID = "entry_pid"
    SHUTDOWN = "shutdown"
    RESTART = "restart"
    ANSWER_SHUTDOWN = "answer_shutdown"
    ANSWER_RESTART = "answer_restart"
    USER_DECLINED = "declined"
    BOT_LOGS = "get_bot_logs"
    SYSTEM_LOGS = "get_system_logs"